# Simple set of rules for GitHub actions integration with a ROS project
#

name: Compiling Test

on:
  push:
    branches:
      - melodic-devel
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: melodic
      - name: Install dependencies
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: simple_laser_geometry
          target-ros1-distro: melodic